# Generated by Django 3.0.7 on 2020-08-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('students', '0005_auto_20200818_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
