# Generated by Django 3.0.7 on 2020-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
