# Generated by Django 3.0.7 on 2020-08-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teachers', '0013_queue_display'),
        ('students', '0007_feedback_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHoursLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oh_lines', to='teachers.Queue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oh_lines', to='users.Student')),
            ],
        ),
    ]
