# Generated by Django 3.0.7 on 2020-08-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_officehoursline'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehoursline',
            name='got_help',
            field=models.BooleanField(default=False),
        ),
    ]
