# Generated by Django 3.0.7 on 2020-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_officehoursline_time_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehoursline',
            name='has_student_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officehoursline',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officehoursline',
            name='student_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
