# Generated by Django 3.0.7 on 2020-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20200819_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehoursline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
