# Generated by Django 3.0.7 on 2020-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200814_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='frequency',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
