# Generated by Django 3.0.7 on 2020-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200814_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
