# Generated by Django 3.0.7 on 2020-08-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200815_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
