# Generated by Django 3.0.7 on 2020-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_queue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
