# Generated by Django 3.0.7 on 2020-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_queue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
