# Generated by Django 3.0.7 on 2020-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_queue_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
