# Generated by Django 3.0.7 on 2020-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_queue_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='currently_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
