# Generated by Django 3.0.7 on 2020-08-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_queue_currently_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
