# Generated by Django 3.0.7 on 2020-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_queue_has_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
